In [1]:
import numpy as np

In [2]:
# --- Step 1: Create a User-Item Rating Matrix (example dataset) ---
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
], dtype=float)

num_users, num_items = R.shape
k = 2   # Number of latent features

In [3]:
# --- Step 2: Initialize User (P) and Item (Q) matrices randomly ---
np.random.seed(42)
P = np.random.rand(num_users, k)  # User features
Q = np.random.rand(num_items, k)  # Item features

In [4]:
# --- Step 3: Train with Gradient Descent ---
def matrix_factorization(R, P, Q, steps=5000, alpha=0.002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(num_users):
            for j in range(num_items):
                if R[i][j] > 0:  # Only train on known ratings
                    eij = R[i][j] - np.dot(P[i, :], Q[:, j])
                    for k in range(len(P[i, :])):
                        P[i][k] += alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] += alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        # Compute loss
        error = 0
        for i in range(num_users):
            for j in range(num_items):
                if R[i][j] > 0:
                    error += (R[i][j] - np.dot(P[i, :], Q[:, j]))**2
        if step % 1000 == 0:
            print(f"Step {step}: error = {error:.4f}")
    return P, Q.T


In [5]:
# --- Step 4: Train model ---
nP, nQ = matrix_factorization(R, P, Q, steps=5000)

Step 0: error = 105.1990
Step 1000: error = 0.0216
Step 2000: error = 0.0031
Step 3000: error = 0.0028
Step 4000: error = 0.0028


In [6]:
# --- Step 5: Reconstruct Full Rating Matrix ---
R_pred = np.dot(nP, nQ.T)

print("\nOriginal Ratings (with 0 = unknown):")
print(R)
print("\nPredicted Ratings (Matrix Factorization):")
print(np.round(R_pred, 2))


Original Ratings (with 0 = unknown):
[[5. 3. 0. 1.]
 [4. 0. 0. 1.]
 [1. 1. 0. 5.]
 [1. 0. 0. 4.]
 [0. 1. 5. 4.]]

Predicted Ratings (Matrix Factorization):
[[4.98 2.98 4.13 1.  ]
 [3.98 2.4  3.52 1.  ]
 [1.   0.99 5.93 4.97]
 [1.   0.91 4.87 3.98]
 [1.17 1.01 4.98 3.99]]
